venue:
  name: BINANCE
  account_type: CASH
  oms_type: NETTING
  starting_balances:
    - amount: 100000
      currency: USDT

strategy:
  module: strategy
  class: VeydriftStrategy
  config_class: VeydriftStrategyConfig
  config:
    order_id_tag: "001"

instruments:
  - id: BTCUSDT.BINANCE
    kind: spot
    raw_symbol: BTCUSDT
    base_currency: BTC
    quote_currency: USDT
    price_precision: 2
    size_precision: 6
    price_increment: "0.01"
    size_increment: "0.000001"
    lot_size: "0.000001"
    maker_fee: "0.0002"
    taker_fee: "0.0005"
    bar_type: BTCUSDT.BINANCE-1-HOUR-LAST-EXTERNAL

  - id: ETHUSDT.BINANCE
    kind: spot
    raw_symbol: ETHUSDT
    base_currency: ETH
    quote_currency: USDT
    price_precision: 2
    size_precision: 5
    price_increment: "0.01"
    size_increment: "0.00001"
    lot_size: "0.00001"
    maker_fee: "0.0002"
    taker_fee: "0.0005"
    bar_type: ETHUSDT.BINANCE-1-HOUR-LAST-EXTERNAL

